// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsrEtxxGBy0Ta--rjn9JTqs01Mni2Q7XQ',
    appId: '1:301803721911:web:52d1cded48df942090a932',
    messagingSenderId: '301803721911',
    projectId: 'fanpoll-6e35e',
    authDomain: 'fanpoll-6e35e.firebaseapp.com',
    storageBucket: 'fanpoll-6e35e.firebasestorage.app',
    measurementId: 'G-6NJT5GLNS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXJL1jaE2HqZ9VaBul6wIvKu0RNUMJQX8',
    appId: '1:301803721911:android:12f1026ee373f48890a932',
    messagingSenderId: '301803721911',
    projectId: 'fanpoll-6e35e',
    storageBucket: 'fanpoll-6e35e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjbsR2GIzF8_2NxhlXrGxI7pQOJ-YE1jo',
    appId: '1:301803721911:ios:3aae2f6ff8c4ce3690a932',
    messagingSenderId: '301803721911',
    projectId: 'fanpoll-6e35e',
    storageBucket: 'fanpoll-6e35e.firebasestorage.app',
    iosClientId: '301803721911-mhi1e68ujjn4cqurpd2qfj1oajfgko65.apps.googleusercontent.com',
    iosBundleId: 'com.fanpoll.fanPoll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjbsR2GIzF8_2NxhlXrGxI7pQOJ-YE1jo',
    appId: '1:301803721911:ios:3aae2f6ff8c4ce3690a932',
    messagingSenderId: '301803721911',
    projectId: 'fanpoll-6e35e',
    storageBucket: 'fanpoll-6e35e.firebasestorage.app',
    iosClientId: '301803721911-mhi1e68ujjn4cqurpd2qfj1oajfgko65.apps.googleusercontent.com',
    iosBundleId: 'com.fanpoll.fanPoll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjbsR2GIzF8_2NxhlXrGxI7pQOJ-YE1jo',
    appId: '1:301803721911:web:bed5e503157f501490a932',
    messagingSenderId: '301803721911',
    projectId: 'fanpoll-6e35e',
    authDomain: 'fanpoll-6e35e.firebaseapp.com',
    storageBucket: 'fanpoll-6e35e.firebasestorage.app',
    measurementId: 'G-FDWZBD4Z7R',
  );
}
